[package]
name = "ukeyskf"
version = "0.1.0"
edition = "2021"

[dependencies]
asn1-rs = "0.6.2"
base64 = "0.22.1"
chrono = "0.4.38"
eframe = "0.29.1"
libloading = "0.8.5"
screen_size = "0.1.0"
x509-parser = "0.16.0"
